version: '3'
services:
  my-mysql-container:
    image: mysql
    container_name: my-mysql-container
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  api:
    container_name: api
    image: pet-project-img
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    restart: always

volumes:
  container-volume: